# Generated by Django 5.1.1 on 2024-10-03 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='app_cad_usuarios.empresa')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='app_cad_usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PessoasProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_projetos', to='app_cad_usuarios.empresa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_projetos', to='app_cad_usuarios.projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_projetos', to='app_cad_usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='app_cad_usuarios.usuario'),
        ),
    ]
